
child_modules:
  # - name: qubership-monitoring-operator
  #   version: 1.0.0
  #   version_path: monitoringOperator.image
  #   module_string: registry:port/path/to/monitoring-operator-image:${version}
  # - name: qubership-vmauth
  #   version: 1.0.0
  #   version_path: victoriametrics.vmAuth
  #   module_string: registry:port/path/to/vmauth-image:${version}
  # - name: qubership-vmSingle
  #   version: 1.0.0
  #   version_path: victoriametrics.vmSingle
  #   module_string: registry:port/path/to/vmsingle-image:${version}
  - name: module1
    version: 1.0.0
    version_path: module1.image
    module_string: registry:port/path/to/module1-image:${version}
  - name: module2
    version: 2.0.0
    version_path: module2.image
    module_string: registry:port/path/to/module2-image:${version}
  - name: module3
    version: 3.0.0
    version_path: module3.image
    module_string: registry:port/path/to/module3-image:${version}

config_file: charts/values.yaml

# monitoringOperator:
#   image: registry:port/path/to/monitoring-operator-image:tag

# victoriametrics:
#   vmAuth:
#     image: registry:port/path/to/vmauth-image:tag
#   vmSingle:
#     image:  registry:port/path/to/vmsingle-image:tag