name: "Get repository list"
on:
  workflow_dispatch
permissions:
  contents: read
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: "Get repos"
        run: |
          repos=$(curl -sL \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/orgs/MyBorislavrOrg/repos?type=public&page=1&per_page=200" | jq -r 'sort_by(.name) | .[] | .name')
          echo ${repos}
    
