---

name: Multi-module release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        type: string
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  get-child-modules:
    outputs:
      modules: ${{ steps.get-child-modules.outputs.modules }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Get child modules"
        id: get-child-modules
        run: |
          echo "modules=$(jq -c '.child_modules | map(.name)' ./.github/.child-modules.json)" >> $GITHUB_OUTPUT
        shell: bash
  release:
    needs: get-child-modules
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.get-child-modules.outputs.modules) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Get module version"
        id: get-module-version
        run: |
          echo "module-version=$(jq '.child_modules[] | select(.name == "${{ matrix.module }}") | .version' ./.github/.child-modules.json)"
          echo "module-version=$(jq '.child_modules[] | select(.name == "${{ matrix.module }}") | .version' ./.github/.child-modules.json)" >> $GITHUB_OUTPUT
        shell: bash
      - name: "Trigger release"
        uses: nookyo/qubership-workflow-hub/actions/custom-event@main
        with:
          github-token: ${{ secrets.REMOTE_TRIGGER_TOKEN }}
          repo: ${{ matrix.module }}
          owner: ${{ github.repository_owner }}
          event_type: remote_release_trigger
          client_payload: |
            {
              "version": ${{ steps.get-module-version.outputs.module-version }}
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
